### ISSUE TITLE
Research: Relay Network

### ISSUE THREAD

**Issue by fabianschu** [Curve-Labs/lit-privacy#4]
**Background**
- the sdk sends the privacy-preserving meta tx to a relay network: https://github.com/Curve-Labs/lit-privacy-sdk/issues/3 
- we haven't specified which relay mechanism to use
- potential candidates: Gas Station Network (GSN), Gelato Relay

**Acceptance Criteria**

- [ ] compared GSN and Gelato (and others if relevant) and identified the best fit

**Comment by codebuster22** [comment]
I have previously used Gelato Relay (https://docs.gelato.network/developer-services/relay).
I can pick it up for the research

**Comment by codebuster22** [comment]
@fabianschu 
Did a small comparison between Gelato and OpenGSN.
https://www.notion.so/curvelabs/Open-GSN-relayer-vs-Gelato-Relayer-971a9823b65441ae9bc6d0938f271984?pvs=4

**Comment by fabianschu** [comment]
Is it possible to DoS either of the two systems?

In other words, can a malicious person spam a bunch of failing transactions to the relay until all gas money is spent?

**Comment by codebuster22** [comment]
@fabianschu 
> Is it possible to DoS either of the two systems?
> 
> In other words, can a malicious person spam a bunch of failing transactions to the relay until all gas money is spent?

Both have mechanism to prevent it, though OpenGSN does it better. How? before relaying the transaction, OpenGSN will dry-run the transaction and only send if dry-run succeeds. I'm not sure if Gelato does a dry-run before relaying transaction. I'll ask them on discord.

**Comment by codebuster22** [comment]
We will not specify any Relayer network. We will ask the user to pass the relayer provider so that a relay transaction can be made as a callback.

**Comment by codebuster22** [comment]
this will be taken care in #3
